# Site settings
title: Honeypot Blog
email: team@honeypot.io
description: > # this means to ignore newlines until "baseurl:"
  Blog of awesome Honeypot
url: "http://blog.honeypot.io"
twitter_username: honeypotio
github_username:  teamhoneypot

# Build settings
markdown: kramdown

#SASS
sass:
  sass_dir: _sass
  style: compressed

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

defaults:
  -
    scope:
      path: ""
    values:
      excerpt_separator: <!--more-->
